### ISSUE TITLE
Linux: Fatal Error: System.ArgumentOutOfRangeException: Capacity must be positive.

### ISSUE THREAD

**Issue by santiagocasas** [flickr-downloadr/flickr-downloadr-gtk#102] opened 2019-04-15 05:23 UTC
~/flickrdownloadr$ ./flickrdownloadr
Mozilla Roots Importer - version 4.6.2.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

WARNING: mozroots is deprecated, please move to cert-sync instead.

Downloading from 'https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt'...
Importing certificates into user store...
151 new root certificates were added to your trust store.
Import process completed.

Fatal Error: System.ArgumentOutOfRangeException: Capacity must be positive.
Parameter name: capacity
  at FloydPink.Flickr.Downloadr.UI.Windows.BaseWindow+<>c__DisplayClass3_0.<HandleException>b__0 (System.Object <p0>, System.EventArgs <p1>) [0x00000] in <9fd91914e0084e658662b1d8e5070801>:0 
  at Gtk.Application+InvokeCB.Invoke () [0x00000] in <7a41aae9f05e45b7b5a8cedfab67f8ff>:0 
  at GLib.Timeout+TimeoutProxy.Handler (System.IntPtr data) [0x0003c] in <5a439e0caae7469886e7119d9f6bc621>:0  ... Fal

**Comment by PeterFisk** [comment] 2019-04-19 21:52
I get the same error on Windows:

<log4j:event logger="FloydPink.Flickr.Downloadr.UI.MainClass" timestamp="1555710280035" level="FATAL" thread="1">
	<log4j:message>Unhandled Exception.</log4j:message>
	<log4j:properties>
		<log4j:data name="log4jmachinename" value="LAPTOP-000" />
		<log4j:data name="log4japp" value="flickr-downloadr.exe" />
		<log4j:data name="log4net:Identity" value="" />
		<log4j:data name="log4net:UserName" value="LAPTOP-000\Usr000" />
		<log4j:data name="log4net:HostName" value="LAPTOP-000" />
	</log4j:properties>
	<log4j:throwable>
		<![CDATA[System.ArgumentOutOfRangeException: Kapasiteten må være positiv.
Parameternavn: capacity
   ved FloydPink.Flickr.Downloadr.UI.Windows.BaseWindow.<>c__DisplayClass3_0.<HandleException>b__0(Object <sender>, EventArgs <e>)
   ved Gtk.Application.InvokeCB.Invoke()
   ved GLib.Timeout.TimeoutProxy.Handler()]]>
	</log4j:throwable>
	<log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.MainClass" method="OnUnhandledException" file="" line="0" />
</log4j:event>
<log4j:event logger="FloydPink.Flickr.Downloadr.UI.Windows.FatalErrorWindow" timestamp="1555710280035" level="DEBUG" thread="1">
	<log4j:message>ctor</log4j:message>
	<log4j:properties>
		<log4j:data name="log4jmachinename" value="LAPTOP-000" />
		<log4j:data name="log4japp" value="flickr-downloadr.exe" />
		<log4j:data name="log4net:Identity" value="" />
		<log4j:data name="log4net:UserName" value="LAPTOP-000\Usr000" />
		<log4j:data name="log4net:HostName" value="LAPTOP-000" />
	</log4j:properties>
	<log4j:locationInfo class="FloydPink.Flickr.Downloadr.UI.Windows.FatalErrorWindow" method=".ctor" file="" line="0" />
</log4j:event>

**Comment by kylegordon** [comment] 2019-05-25 22:12
Same issue here

Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

flickr-downloadr v3.2.0.1

**Comment by cutedaffodil** [comment] 2019-06-04 01:35
Duplicate of #103

**Closed by cutedaffodil** 2019-06-04 01:35 UTC
Labels: bug, help wanted
