### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by dennisjcox** [flickr-downloadr/flickr-downloadr-gtk#101] opened 2019-03-31 12:02 UTC
[flickrdownloadr.log](https://github.com/flickr-downloadr/flickr-downloadr-gtk/files/3026549/flickrdownloadr.log)

Hi - giving the application a try and I got a unhandled exception off the bat. I'm sure its something silly that I did wrong.

**Comment by tamrajohnosn** [comment] 2019-05-30 22:07
I'm having the same problem. I'm guessing it still isn't resolved?

**Comment by cutedaffodil** [comment] 2019-06-04 01:35
Duplicate of #103

**Closed by cutedaffodil** 2019-06-04 01:35 UTC
Labels: bug, help wanted
